name: Create Release and Publish

on:
  push:
    tags:
      - "v*"

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Setup pnpm
      uses: pnpm/action-setup@v2.2.4
      with:
        version: 8.6.0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm run --if-present lint
    - run: pnpm run --if-present build
  release:
    runs-on: "ubuntu-latest"
    needs: check
    steps:
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
  publish:
    runs-on: ubuntu-latest
    needs: release
    steps:
    - uses: actions/checkout@v3
    - name: Setup pnpm
      uses: pnpm/action-setup@v2.2.4
      with:
        version: 8.6.0
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        cache: 'pnpm'
        node-version: 18.x
        registry-url: 'https://registry.npmjs.org'
    - run: pnpm install
    - run: pnpm run --if-present build
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
